SecurityControl/force-app/main/default/objects/Security_Alert__c/Security_Alert__c.object-meta.xml
<CustomObject>
    <label>Security Alert</label>
    <nameField>
        <displayFormat>Alert-{0000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SecurityControl/force-app/main/default/objects/Security_Alert__c/fields/Camera_ID__c.field-meta.xml
<CustomField>
    <fullName>Camera_ID__c</fullName>
    <label>Camera ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SecurityControl/force-app/main/default/objects/Security_Alert__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

SecurityControl/force-app/main/default/objects/Security_Alert__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>False Alarm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SecurityControl/force-app/main/default/objects/Security_Alert__c/fields/Threat_Type__c.field-meta.xml
<CustomField>
    <fullName>Threat_Type__c</fullName>
    <label>Threat Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

SecurityControl/force-app/main/default/objects/Security_Alert__c/fields/Weapon__c.field-meta.xml
<CustomField>
    <fullName>Weapon__c</fullName>
    <label>Weapon</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

SecurityControl/force-app/main/default/classes/SecurityDashboardController.cls
public with sharing class SecurityDashboardController {
    @AuraEnabled(cacheable=false)
    public static List<Security_Alert__c> getLatestAlerts() {
        Datetime cutoff = Datetime.now().addMinutes(-10);
        return [
            SELECT Id, Camera_ID__c, Location__c, Confidence__c, Status__c, Threat_Type__c, Weapon__c ,Video_ID__c
            FROM Security_Alert__c
            WHERE CreatedDate >= :cutoff
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
        ];
    }
}